version: "3"
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"

  auth-service:
    build: ./auth-service
    ports:
      - "5001:5001"

  blog-service:
    build: ./blog-service
    ports:
      - "5002:5002"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"